const lzpSl = [
  [
    {item:'f',index:'as',id:1},
    {item:'a',index:'asd',id:2}
  ],
  [
    {item:'a',index:'as',id:1},
    {item:'a',index:'asd',id:2}
  ],
  [
    {item:'d',index:'as',id:1},
    {item:'a',index:'asd',id:2}
  ],
  [
    {item:'f',index:'as',id:1},
    {item:'a',index:'asd',id:2}
  ],
  [
    {item:'g',index:'as',id:1},
    {item:'a',index:'asd',id:2}
  ]
]
const lzpSl2 = [
    [
        {item:'aaa',key:'1'},
        {item:'aaa',key:'2'},
        {item:'aaa',key:'3'},
        {item:'aaa',key:'4'}
    ],
    [
        {item:'哦哦哦',key:'1'},
        {item:'哦哦哦',key:'2'},
        {item:'哦哦哦',key:'3'},
        {item:'哦哦哦',key:'4'}
    ],
    [
        {item:'呃呃呃',key:'1'},
        {item:'呃呃呃',key:'2'},
        {item:'呃呃呃',key:'3'},
        {item:'呃呃呃',key:'4'}
    ]
]

const centerConfig = {
    route:[
        {item:'aaa',key:'1'},
        {item:'aaa',key:'2'},
        {item:'aaa',key:'3'},
        {item:'aaa',key:'4'}
    ],
    todo:[
        [
          {item:'f',index:'as',id:1},
          {item:'a',index:'asd',id:2}
        ],
        [
          {item:'a',index:'as',id:1},
          {item:'a',index:'asd',id:2}
        ],
        [
          {item:'d',index:'as',id:1},
          {item:'a',index:'asd',id:2}
        ],
        [
          {item:'f',index:'as',id:1},
          {item:'a',index:'asd',id:2}
        ],
        [
          {item:'g',index:'as',id:1},
          {item:'a',index:'asd',id:2}
        ]
    ]
}

export {
    centerConfig
}